name: Bot Deploy

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy-bot:
    name: NFS-MusicBot
    runs-on: ubuntu-latest
    container: anggit86/musicbot:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

      - name: clone source
        run: |
          git config --global user.email jarbull86@gmail.com
          git config --global user.name NFS86
          cd
          git https://github.com/NFS86/RadioPlayerV3 /RadioPlayerV3
          cd && cd /RadioPlayerV3
          curl $CONFIG_FILE_URL -o config.env
        env:
         CONFIG_FILE_URL: ${{secrets.CONFIG}}

      - name: Run Bot..
        run: |
          cd && cd /RadioPlayerV3
          python3 main.py &
          sleep 300m

      - name: Commit auto run and changes DataBase
        run: |
          git config --local user.email "jarbull86@gmail.com"
          git config --local user.name "NFS86"
          git add backups/backup.sql
          git commit --allow-empty -m "NFS-MusicBot Deploy | $(/bin/date)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
