name: Bot Deploy

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy-bot:
    name: NFS-MusicBot
    runs-on: ubuntu-latest
    container: anggit86/musicbot:latest

    services:
      postgres:
        image: postgres:9.6.20
        env:
          POSTGRES_DB: nfs-musicbot
          POSTGRES_PASSWORD: bebas
          POSTGRES_PORT: 5432
          POSTGRES_USER: nfs86
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: clone source
        run: |
          git config --global user.email jarbull86@gmail.com
          git config --global user.name NFS86
          cd
          git clone https://NFS86:$GH_TOKEN@github.com/NFS86/VCPlayBot /app
          cd && cd /app
          curl $CONFIG_FILE_URL -o local.env
        env:
         GH_TOKEN: ${{secrets.GH_TOKEN}}
         CONFIG_FILE_URL: ${{secrets.CONFIG}}

      - name: Run Bot..
        run: |
          cd && cd /app
          python3 -m VCPlayBot &
          sleep 2m

      - name: Run pg_dump
        uses: tj-actions/pg-dump@v2.3
        with:
          database_url: "postgres://nfs86:bebas@postgres:5432/nfs-musicbot"
          path: "backups/backup.sql"

      - name: Check changes to backup file.
        id: changed_backup
        uses: tj-actions/verify-changed-files@v10
        with:
          files: backups/backup.sql

      - name: Commit auto run and changes DataBase
        run: |
          git config --local user.email "jarbull86@gmail.com"
          git config --local user.name "NFS86"
          git add backups/backup.sql
          git commit --allow-empty -m "NFS-MusicBot Deploy | $(/bin/date)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
